fragment Cart on Cart {
  id
  paymentMethod{
    ...PaymentMethod
  }
  deliveryAddress {
    ...Address
  }
  deliveryMethod {
    ...DeliveryMethod
  }
  subtotalPrice {
    ...Price
  }
  taxPrice {
    ...Price
  }
  deliveryPrice {
    ...Price
  }
  totalPrice {
    ...Price
  }
  quantity
  cartItems {
    ...CartItem
  }
}
