fragment Order on Order {
  id
  deliveryAddress {
    ...Address
  }
  deliveryMethod {
    ...DeliveryMethod
  }
  paymentMethod {
    ...PaymentMethod
  }
  subtotalPrice {
    ...Price
  }
  taxPrice {
    ...Price
  }
  deliveryPrice {
    ...Price
  }
  totalPrice {
    ...Price
  }
  status
  orderItems {
    ...OrderItem
  }
  orderHistories {
    ...OrderHistory
  }
  createdAt
}
