fragment Product on Product {
  id
  title
  description
  brand {
    ...Brand
  }
  media {
    ...Media
  }
  colors {
    ...Color
  }
  sizes {
    ...Size
  }
  productVariants {
    ...ProductVariant
  }
}
