fragment User on User {
  id
  firstName
  lastName
  fullName
  phone
  emailAddress {
    ...EmailAddress
  }
  avatar {
    url
  }
  roles {
    ...Role
  }
  permissions {
    ...Permission
  }
}
