query Colors($filter: ColorFilter, $paging: OffsetPaging, $sorting: [ColorSort!]) {
  colors(filter: $filter, paging: $paging, sorting: $sorting) {
    nodes {
      id
      code
      name
      hex
    }
  }
}
