query Products($filter: ProductFilter, $paging: OffsetPaging, $sorting: [ProductSort!]) {
  products(filter: $filter, paging: $paging, sorting: $sorting) {
    nodes {
      ...Product
    }
    totalCount
  }
}
