"use client";

import {
  Add,
  BadgeOutlined,
  Check,
  CloseRounded,
  DarkMode,
  EmailOutlined,
  ExpandMoreRounded,
  Facebook, Favorite, FavoriteBorder,
  FavoriteBorderOutlined,
  Instagram,
  KeyOutlined,
  LightMode,
  MenuRounded,
  Person,
  PersonOutlineOutlined,
  PhoneOutlined, Remove,
  Search,
  ShoppingCartOutlined,
  Sort,
  Storefront,
  Telegram,
  Twitter,
  VisibilityOffOutlined,
  VisibilityOutlined,
} from "@mui/icons-material";

const Icons = {
  LightMode: LightMode,
  DarkMode: DarkMode,
  Wishlist: FavoriteBorderOutlined,
  Cart: ShoppingCartOutlined,
  Person: PersonOutlineOutlined,
  PersonLoggedIn: Person,
  Hamburger: MenuRounded,
  Close: CloseRounded,
  Facebook: Facebook,
  Instagram: Instagram,
  Telegram: Telegram,
  Twitter: Twitter,
  Email: EmailOutlined,
  Phone: PhoneOutlined,
  Credentials: BadgeOutlined,
  Key: KeyOutlined,
  Visibility: VisibilityOutlined,
  VisibilityOff: VisibilityOffOutlined,
  Check: Check,
  ExpandMore: ExpandMoreRounded,
  Sort: Sort,
  Search: Search,
  Stock: Storefront,
  Like: FavoriteBorder,
  Unlike: Favorite,
  Add: Add,
  Remove: Remove
};

export default Icons;

